### ISSUE TITLE
请问这个链接下的解密方法代码可以贴一下吗https://the-x.cn/cryptography/Aes.aspx

### ISSUE THREAD

**Issue by hel2o** [cbanor/X-Website#1]
https://the-x.cn/cryptography/Aes.aspx
![图片](https://user-images.githubusercontent.com/14226648/144796412-685493f0-d4be-4aaf-995d-14e0a2849c9c.png)

**Comment by cbanor** [comment]
参考：[https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes?view=net-6.0](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes?view=net-6.0)
