### ISSUE TITLE
大佬你好

### ISSUE THREAD

**Issue by zdb1993** [cbanor/X-Website#10]
我是前端开发 使用你网站内的rsa解密可以成功 
自己本地的uniapp使用JSEncrypt的解密有些简单的加密值能解密出来复杂的就返回null 想知道您网址的方法有前端的解密api可以使用吗

**Comment by cbanor** [comment]
您好。我们使用的是后端加/解密的方式。前端只是一个简单的调用。目前没有免费公开接口的计划。
