### ISSUE TITLE
密钥输入长度限制问题

### ISSUE THREAD

**Issue by Alexzzzzzz1** [cbanor/X-Website#11]
在https://the-x.cn/cryptography/Aes.aspx的密码一栏粘贴比如123456789123456789，实际上在输入框被截断成了1234567891234567,如果是字母，不只会截断，而且可能修改

**Comment by cbanor** [comment]
此处密钥长度是被强行截断的。其原因是你输入的密钥超过了算法要求的密钥长度。AES密码长度与bits相关。

**Comment by Alexzzzzzz1** [comment]
好的好的
